from fastapi import APIRouter
from models.schemas import AuditLogEntry
from datetime import datetime

router = APIRouter(prefix="/api/audit-trail", tags=["audit"])


@router.get("/{alert_id}", response_model=list[AuditLogEntry])
async def get_audit_trail(alert_id: str):
    """Get audit trail for a specific alert"""
    # Mock audit trail data
    mock_audit_logs = [
        AuditLogEntry(
            timestamp=datetime.fromisoformat("2025-10-30T09:15:00"),
            user="Ana Rodriguez",
            action="Alert Created",
            details="Alert automatically generated by Transaction Monitor Agent",
            alert_id=alert_id,
        ),
        AuditLogEntry(
            timestamp=datetime.fromisoformat("2025-10-30T09:20:00"),
            user="Ana Rodriguez",
            action="Alert Viewed",
            details="Compliance officer viewed alert details",
            alert_id=alert_id,
        ),
        AuditLogEntry(
            timestamp=datetime.fromisoformat("2025-10-30T09:25:00"),
            user="Document Forensics Agent",
            action="Document Analysis Completed",
            details="3 issues detected in submitted documentation",
            alert_id=alert_id,
        ),
    ]
    return mock_audit_logs

